# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170817_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_top_user',
            field=models.CharField(default='NO TOP USER!', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tokens',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
